# THIS ONLY WORK ON 127.0.0.1:3000
RECAPTCHA_PUBLIC_KEY: '6LdO6R8TAAAAAK4JOgsXtpNz3O-W0xT_DEaqxNMo'
RECAPTCHA_PRIVATE_KEY: "6LdO6R8TAAAAAM7okxh79m94rOYm9yR2lZNYcJrR"

# OFFICE 365
OFFICE365_KEY: '0697591a-bada-4d03-8354-f4ad3dd4493b'                         # Client ID
OFFICE365_SECRET: 'vZ08XLidgRxskGd2kqJzHcd'    # Client Secret